services:
  ### PHP-FPM Container #######################################
  php-fpm:
    build:
      context: ./docker/php-fpm
      dockerfile: Dockerfile
      args:
        user: laravel
        uid: 1000
    working_dir: /var/www/
    volumes:
      - ./app:/var/www
      - ./docker/php-fpm/php.ini:/usr/local/etc/php/php.ini
    ports:
      - "5173:5173"
    expose:
      - "9000"
      - "9003"
    extra_hosts:
      # IMPORTANT: Replace with your Docker Host IP (will be appended to /etc/hosts)
      - "dockerhost:127.0.0.1"
    environment:
      # IMPORTANT: Set the Remote Interpreter entry matching name to `laravel`
      - PHP_IDE_CONFIG=serverName=localhost
      - XDEBUG_CONFIG=remote_host=127.0.0.1
    networks:
      - app-network
    restart: always

  ### Nginx Server Container ##################################
  nginx:
    image: nginx:alpine
    volumes:
      - ./app:/var/www
      - ./docker/php-fpm/nginx/:/etc/nginx/conf.d
    restart: always
    ports:
      - "80:80"

    networks:
      - app-network

  ### MariaDB Container ######################################
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel_password
    volumes:
      - ./.docker/mariadb:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app-network
    restart: always
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-p root_password" ]
      retries: 3
      timeout: 5s

networks:
  app-network:
    driver: bridge
